### ISSUE TITLE
[Bug] go back 

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#126]
### Description

the < button seems to function slightly different then intended.

### Hardware Specification

Operating system: iOS 16.7.1
RAM: 
Cores:
Device: Iphone X

Same on desktop Ubuntu 22.04

### Steps to Reproduce the Bug

1. Create profile
2. Go to Settings/My profile/Profile name
3. Click update (not necessary to actually edit your name, but in both cases the bug will appear)
4. Now click the < button in the top left and it will actually take you back to the edit profile name page instead of back into the menu

### Expected Behaviour

I expect the < button to simply perform a ```cd ..``` like action.

### Actual Behaviour

the < button goes back in more of a browser style, literally the previous tab.

### Errors

no errors

**Comment by JelleMillenaar** [comment]
Was duplicated by @daniel-mader in #134 but keeping that as it has a bit more detailed information.
