### ISSUE TITLE
[Bug] Image shows fallback slot while asset is loading

### ISSUE THREAD

**Issue by daniel-mader** [impierce/identity-wallet#182]
### Description

While an image is loaded from disk using the `<Image />` component, for a brief moment the fallback slot is rendered. While this works as designed, it can confuse the user since the image is _almost_ instantly loaded (aka "placeholder flashing").

### Steps to Reproduce the Bug

1. navigate around the app and pay attention to wherever images are displayed

### Expected Behaviour

Images should be preloaded before the navigation is executed to prevent flashing placeholders, but this might introduce an artificial delay and introduce bad UX

### Actual Behaviour

https://github.com/impierce/identity-wallet/assets/45594838/6f6edb1c-b093-4a0b-a284-ed15d283b2d0

### Errors

n/a

**Comment by maiertech** [comment]
Obsolete with `/credential` route redesign in #366.
