### ISSUE TITLE
feat: compartmentalize ActionType

### ISSUE THREAD

**Issue by nanderstabel** [impierce/identity-wallet#19]
### Description

Compartmentalize `ActionType` into smaller enums grouped by the action prefix (`[dev]`, `[settings`]) etc..

### Motivation

This will keep the action list clean and structured once more actions are added in the future.

### Resources

Perhaps this will offer a nice solution: https://docs.rs/strum/latest/strum/

### To-do List

- [ ] compartmentalize ActionType

**Comment by Oran-Dan** [comment]
issue #97
