### ISSUE TITLE
[Bug] Multiple failures when running shenron profile

### ISSUE THREAD

**Issue by Norlock** [impierce/identity-wallet#218]
### Description

If i click for example on the ferris profile and then load shenron profile (all steps + resetting profile). I have multiple issues

### Hardware Specification

Operating system:
Device: Linux (tauri desktop)

### Steps to Reproduce the Bug

1. Load ferris profile
2. Load shenron profile (all steps + reset profile)

### Expected Behaviour

Icons loaded, theme correct 

### Actual Behaviour

![image](https://github.com/impierce/identity-wallet/assets/7510943/2ea42fd4-34b0-4989-8889-88575b6e641f)

![image](https://github.com/impierce/identity-wallet/assets/7510943/2226ddd2-b8d5-45cf-b5bf-e8197c3386ef)

### Errors

See above

**Comment by JelleMillenaar** [comment]
Superseded by https://github.com/impierce/identity-wallet/issues/299 as that will fix the issue

**Comment by JelleMillenaar** [comment]
Superseded by https://github.com/impierce/identity-wallet/issues/299 as that will fix the issue
