### ISSUE TITLE
feat: add proper logging and error handling system

### ISSUE THREAD

**Issue by nanderstabel** [impierce/identity-wallet#25]
### Description

Add a system for logging info and debug messages as well as error handling.

Also, add a warning/notification to show to the user when some flow cannot be continued due to external service not responding as expected or not responding at all. 

### Motivation

This will allow for easier debugging both when testing locally as well as on a physical device. 

### Resources

n/a

### To-do List

- [x] logging and error handling system
- [x] add warning/notification

**Comment by JelleMillenaar** [comment]
@nanderstabel Please update this issue to the latest state and requirements.
