### ISSUE TITLE
test: zip 'actions' and 'expected_state' in `assert_state_update`

### ISSUE THREAD

**Issue by nanderstabel** [impierce/identity-wallet#52]
### Description
Currently the function parameters for `assert_state_update` looks like this:
```
pub async fn assert_state_update(
    current_state: AppState,
    actions: Vec<Action>,
    expected_states: Vec<Option<TransferState>>,
)
```

But it makes more sense to combine `actions` and `expected_state` into on single `Vec<(Action, Option<TransferState>)>`:
```
pub async fn assert_state_update(
    current_state: AppState,
    actions: Vec<(Action, Option<TransferState>)>,
)
```

This also means that in the actual tests where `assert_state_update` is called, the two vectors need to be zipped together.

### Motivation

Every element in in the new vector will be a tuple with the an `Action` and the corresponding expected state update.

### Resources
tracking issue: https://github.com/impierce/identity-wallet/issues/50
zip two arrays:

* https://doc.rust-lang.org/stable/std/iter/fn.zip.html

### To-do List

- [ ]

**Comment by Oran-Dan** [comment]
we can close this issue right Nander?
